from typing import Any

class Extractor:
    def __getitem__(self, key: str) -> Any: ...
    @property
    def FrequencySettings(self) -> Any: ...
    @property
    def Outputs(self) -> Any: ...

def GetResult(entity_path: str, result_type: str) -> Any: ...

em_evaluators: Any
