from typing import Any

def IsOpen(project_path: str) -> bool: ...
def AllEntities() -> list[Any]: ...
def GetEntity(name: str) -> Any: ...
@property
def AllSimulations(self) -> list[Any]: ...
def Close() -> None: ...
def New() -> None: ...
def SaveAs(path: str) -> None: ...
