from typing import Any

def IsOpen(project_path: str) -> bool: ...
def AllEntities() -> list[Any]: ...
def GetEntity(name: str) -> Any: ...
def AllSimulations() -> list[Any]: ...
def Close() -> None: ...
def New() -> None: ...
def SaveAs(path: str) -> None: ...
