from typing import Any

class analysis:
    class Extractor:
        def __getitem__(self, key: str) -> Any: ...
        @property
        def FrequencySettings(self) -> Any: ...
        @property
        def Outputs(self) -> Any: ...

    def GetResult(entity_path: str, result_type: str) -> Any: ...

    em_evaluators: Any

class document:
    def IsOpen(project_path: str) -> bool: ...
    def AllEntities() -> list[Any]: ...
    def GetEntity(name: str) -> Any: ...
    def AllSimulations() -> list[Any]: ...
    def Close() -> None: ...
    def New() -> None: ...
    def SaveAs(path: str) -> None: ...

class materials:
    database: Any

simulation: Any
model: Any
units: Any
data: Any
